FROM node:14.17.3-alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
ENV JISOO=perfect
RUN ["yarn","build"]

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html